version: "3.8"


services:

  fpm:
    build: 
      context: ./docker 
      dockerfile: Dockerfile-php 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www/project/:cached
    networks:
      - symfony 

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - 8000:80 
    networks:
      - symfony

  db: 
    image: mariadb:11.0.3
    ports:
      - "3317:3306" #outside:inside
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - persistent:/var/lib/mysql
      - ./docker/build/db/:/docker-entrypoint-initdb.d/ # ./docker/build/db/new_db.sql.gz existing db, if needed
    networks:
      - symfony

networks:
  symfony:

volumes:
  persistent:
  
